


// call the problem function 
problem();


// ------------------------ SETUP FUNCTIONS ----------------------- //
// set up fct to update HTML page
function setUp(number, title, description, solution) {

	// Put the problem data in the HTML Page !
	document.getElementById("problem_number").innerHTML = number;
	document.getElementById("problem_title").innerHTML = title;
	document.getElementById("problem_description").innerHTML = description;

	// Put the solution in the HTML Page !
	document.getElementById("solution_goes_here").innerHTML = solution;
}


// ------------------------ PROBLEMS Functions ---------------------- //

// problem solution !
function problem() {
	// this is the solution 
	let solution;
	let title = "Even Fibonacci numbers";
	let description = 
		"\
		Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:\
		<br>1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\
		<br>By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.\
		";
	// find solution
	let max_value = 4*1000000; 
	solution = sum_fibonacci(1, 1, 0, max_value);
	// set html data 
	setUp(2, title, description, solution);
}

function sum_fibonacci(term_a, term_b, sum, max_value) {
	
	// final condition term > max_value
	if (term_a > max_value){
		return sum;
	}
	// else, sum the rest of the terms
	if(term_a%2 == 0) sum+= term_a;
	if(term_b%2 == 0) sum+= term_b;
	let term_a2 = term_a+term_b;
	let term_b2 = term_a2+term_b;
	console.log("term_a : ", term_a, "term_b : ", term_b, "sum : ", sum);
	return sum_fibonacci(term_a2, term_b2, sum, max_value);


}





